

MAX_TOKEN_MODEL_MAP = {
    "gpt-3.5-turbo": 4096,
}

PDF_SAVE_DIR = "./files/"


DEFAULT_ENGINE = "gpt-3.5-turbo"
DEFAULT_TEMPERATURE = 0.5
DEFAULT_TOP_P = 1
DEFAULT_PRESENCE_PENALTY = 0
DEFAULT_FREQUENCY_PENALTY = 0
DEFAULT_REPLY_COUNT = 1